replicaCount: 1

image:
  repository: janpreet/simple-python-api
  pullPolicy: Always
  tag: "latest"

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false